# Generated by Django 4.2.2 on 2023-07-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheraldevice',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
