# Generated by Django 4.2.2 on 2023-07-12 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_peripheraldevice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheraldevice',
            name='uid',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
